services:

  mariadb:
    image: mariadb
    ports:
      - "3308:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_ALLOW_EMPTY_PASSWORD=false
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
      - MARIADB_DATABASE=northwind
    volumes:
      - "./docker-compose-volume/mariadb:/var/lib/mysql"
      - "./docker-compose-volume/northwind_mysql.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - daneshkarnetwork


  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   ports:
  #     - 9090:80
  #   environment:
  #     - PMA_HOST: mariadb
  #     - PMA_PASSWORD: test
  #   volumes:
  #     - mysql
  #   networks:
  #     - daneshkarnetwork

networks:
  daneshkarnetwork: { }
